name: Enum

on:
  workflow_dispatch:

jobs:
  enum:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - name: lsm param
        run: cat /sys/kernel/security/lsm

      - run: cat /boot/config-`uname -r` | grep CONFIG_BPF_KPROBE_OVERRIDE

      - run: ls -lah /
