name: Enum

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  enum:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: lsm param
        run: cat /sys/kernel/security/lsm

      - run: cat /boot/config-`uname -r` | grep CONFIG_BPF_KPROBE_OVERRIDE

      - run: ls -lah /
