name: Policy Store

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@01071688477c6140fd21e39a41cfbd8b65bba65d # rc
        with:
          policy: block-policy

      # - run: sudo resolvectl flush-caches 
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # - run: |
      #     bash trace_log.sh&
          
      - name: call google
        run: |
          dig google.com
          curl https://google.com
          
          
      - name: call results-receiver.actions.githubusercontent.com
        run: |
          dig results-receiver.actions.githubusercontent.com
          curl https://results-receiver.actions.githubusercontent.com
          echo "Hello from the build job!" > output.txt

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: my-artifact
          path: output.txt

      # - name: print tracer log
      #   if: always()
      #   run: |
      #     sudo cat trace.log
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
         go-version: '1.23.0'
  build-no-policy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@01071688477c6140fd21e39a41cfbd8b65bba65d # rc
        with:
          policy: block-policy1

      # - run: sudo resolvectl flush-caches 
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # - run: |
      #     bash trace_log.sh&
          
      - name: call google
        run: |
          dig google.com
          curl https://google.com
          
          
      - name: call results-receiver.actions.githubusercontent.com
        run: |
          dig results-receiver.actions.githubusercontent.com
          curl https://results-receiver.actions.githubusercontent.com
          echo "Hello from the build job!" > output.txt

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: my-artifact
          path: output.txt

      # - name: print tracer log
      #   if: always()
      #   run: |
      #     sudo cat trace.log
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
         go-version: '1.23.0'
  build-no-id-token:
    needs: build
    runs-on: ubuntu-latest

    steps:

      # - run: sudo resolvectl flush-caches 
  
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@01071688477c6140fd21e39a41cfbd8b65bba65d # rc
        with:
          policy: block-policy
            
      # - name: Checkout code
      #   uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # - run: |
      #     bash trace_log.sh&

      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: my-artifact

      - name: Read artifact content
        run: |
          echo "Contents of artifact:"
          cat output.txt
     
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.23.0'
      # - name: print tracer log
      #   if: always()
      #   run: |
      #     sudo cat trace.log
