name: TLS Basic Tests

on:
  workflow_dispatch:

# permissions:
#   contents: read

permissions:
  contents: read

jobs:
  dynamic-node:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # rc
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      - run: which node
      - uses: actions/setup-node@v4
        with:
          node-version: "16"

      - run: which node

      - run: node req.js

  owner-mismatch:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # rc
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - run: curl -XPOST https://api.github.com/repos/malicious-owner/malicious-repo
