name: 2. Exfiltration Simulation
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  exfiltration-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: block
          allowed-endpoints: >
            *:443
            *:80

      - uses: actions/checkout@v3

      
      - run: curl https://8.8.8.8
         
      # Dependency Confusion DNS Exfiltration Scenario
      - name: DNS Exfiltration
        run: dig google.com
      
      # Codecov Scenario: Exfiltrate data to attacker's endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        run: curl pastebin.com -L
